export const PRODUCT_FEATURED_LIST_REQUEST = "PRODUCT_FEATURED_LIST_REQUEST";
export const PRODUCT_FEATURED_LIST_SUCCESS = "PRODUCT_FEATURED_LIST_SUCCESS";
export const PRODUCT_FEATURED_LIST_FAIL = "PRODUCT_FEATURED_LIST_FAIL";
